---
title: "Tarea 2-ASIES"
author: "Ricardo Bardales"
date: "2024-05-20"
output: rmdformats::downcute
---

##1. Vamos a leer el paquete GPKG 


```{r}
#install.packages("sf")
```
```{r}
library(ggplot2)
```
# Cargar la librería sf
```{r}
library(sf)
```

```{r}
#importamos geopackage desde git hub
linkWorld_gpkg <- "https://raw.githubusercontent.com/Richmaninoff/introgeodf/main/maps/worldMap.gpkg"
```
```{r}
#usamos st_layers para lista de las capas presentes 
sf::st_layers(linkWorld_gpkg) 
```

```{r}
countries=read_sf(linkWorld_gpkg,layer="countryBorders")
rivers=read_sf(linkWorld_gpkg,layer="riverLines")
cities=read_sf(linkWorld_gpkg,layer="cityPoints")
```


```{r}
# Dibujar las capas usando ggplot2

baseLayer=ggplot(data=countries)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=rivers, color='blue') + geom_sf(data=cities, color='red') 
final
```

## Ejercicio 2

Follow the same steps in this last section, but use Peru.
Plot your three layers in R.


```{r}
#Importando paises
Archivo = "C:/Users/Ricardo/Desktop/ASIES-Herramientas cuantitativas/S4. DATA/maps/World_Countries/World_Countries.shp"
countries=st_read(Archivo)
```
```{r}
#importando rios
Archivorios = "C:/Users/Ricardo/Desktop/ASIES-Herramientas cuantitativas/S4. DATA/maps/World_Hydrography/World_Hydrography.shp"

rios=st_read(Archivorios)
```


```{r}
#importando ciudades
Archivocit = "C:/Users/Ricardo/Desktop/ASIES-Herramientas cuantitativas/S4. DATA/maps/World_Cities/World_Cities.shp"

ciudades=st_read(Archivocit)
```


### Creaando el objeto peru
```{r}
library(dplyr)
```

```{r}
peru <- countries %>% filter(COUNTRY == 'Peru')
```
```{r}
citiesperu_clipped <- st_intersection(ciudades, peru)
riversperu_clipped <- st_intersection(rios, peru)
```

```{r}
graficoperu=ggplot(data=peru)  + geom_sf(fill='grey90') + theme_light()
visual1=graficoperu + geom_sf(data=riversperu_clipped, color='blue') + geom_sf(data=citiesperu_clipped, color='red') 
visual1
```


## ejercicio 3. 


```{r}
library(rio)
data=import("pe_airports.csv")
```

```{r}
#Importando los aeropuertos 
Archivo4 = "C:/Users/Ricardo/Desktop/ASIES-Herramientas cuantitativas/S4. DATA/maps/peruoair_4326.shp"
peruoair_4326=st_read(Archivo4)
```
```{r}
#creamos la intersección 
peru_air <- st_intersection(peruoair_4326, peru)
```

```{r}
baseLayer=ggplot(data=peru)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=riversperu_clipped, color='blue') + geom_sf(data=peru_air, color='black') + geom_sf(data=citiesperu_clipped, color='red') + 
  coord_sf(datum = st_crs(peru))
final
```
## ejercicio 4. 

```{r}
#install.packages("remotes")
```
```{r}
library(remotes)
```
```{r}
america="C:/Users/Ricardo/Desktop/ASIES-Herramientas cuantitativas/S4. DATA/maps/America_2023_prjed.gpkg"
sf::st_layers(america)
```

```{r}
ame=read_sf(america,layer="countries")
ame_cen=read_sf(america,layer="centroids")
```

```{r}
library(ggplot2)
baseLayer=ggplot(data=ame)  + geom_sf(fill='grey90') + theme_light() 
E4=baseLayer + geom_sf(data=ame_cen,aes(color=Total_ei5_cat),size=2+ame_cen$Total_ei5) +
    guides(size=NULL) +
  coord_sf(datum = st_crs(ame))

E4
```






